### ISSUE TITLE
Quota Exceed

### ISSUE THREAD

**Issue by iamandreadompe** [IORoot/examples__google-my-business#1]
H, maybe there is a stupid question,
but i'm a newby on the business api, 
ive created a project, i'm trying to test the business api, but for all the business i get the error quota exceed.

How can i solve this?

best regards Andrea

**Comment by IORoot** [comment]
Hey there. 
Apologies, I created this project a while ago and I imagine things have changed since I used it. However, I do remember that the API quota limits are very tight and I had to apply for an increase in the quote credits. You can do that via the google form here: [https://docs.google.com/forms/d/e/1FAIpQLSenhlfSv_Gms-g5wtqcXHbGEXzI_08140cWwwSAtqtoUnm1ig/viewform](https://docs.google.com/forms/d/e/1FAIpQLSenhlfSv_Gms-g5wtqcXHbGEXzI_08140cWwwSAtqtoUnm1ig/viewform)

**Comment by iamandreadompe** [comment]
Thankyou so much!
